# Meta Data for SEO

## Homepage
title = "Akash Network"
titleSeparator = "-"
titleAddition = "Decentralized Computing Marketplace"
description = "Peer-to-Peer Marketplace for Computing Resources"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "akash.network"
titleHome = "Akash Network"

## Twitter Cards
twitterSite = "@akashnet_"
twitterCreator = "@akashnet_"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Akash Network"
schemaAuthor = "Overclock Labs Inc"
schemaAuthorTwitter = "https://twitter.com/ovrclk_"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/gosuri/"
schemaAuthorGitHub = "https://github.com/ovrclk"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/akashnet_"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/akash-network"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = ""

# Feed
copyRight = "Copyright (c) 2022 Overclock Labs Inc"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Mainnet 5 is Live! <a class=\"alert-link stretched-link\" href=\"/blog/mainnet-5-upgrade-instructions-release-notes-and-more/\">Upgrade instructions, release notes, and more.</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/akash-network/akash-network.github.io"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true